# Generated by Django 4.2.7 on 2024-01-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_clients', '0003_fiscalyear_closing_date_fiscalyear_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalyear',
            name='year',
        ),
    ]
