# Generated by Django 4.2.7 on 2024-01-20 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_clients', '0004_remove_fiscalyear_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxclient',
            name='contract_status',
            field=models.CharField(blank=True, choices=[('contract', '契約'), ('cancellation', '解約')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxclient',
            name='zipcode',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{7}$', '郵便番号は7桁の数値で入力してください。')]),
        ),
    ]
