# Generated by Django 4.2.7 on 2024-01-20 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_clients', '0006_alter_taxclient_contract_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxclient',
            name='number',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,6}$', '番号は6桁の半角数字で入力してください。')]),
        ),
    ]
