# Generated by Django 4.2.7 on 2024-01-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_clients', '0007_alter_taxclient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxclient',
            name='corporation_type',
            field=models.CharField(blank=True, choices=[('corporate', '法人'), ('individual', '個人')], max_length=50, null=True),
        ),
    ]
