# Generated by Django 4.2.7 on 2024-01-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_clients', '0008_alter_taxclient_corporation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxclient',
            name='consulting_contract',
            field=models.CharField(blank=True, choices=[('ongoing', '顧問契約'), ('one_time', '単発')], max_length=50, null=True),
        ),
    ]
