# Generated by Django 4.2.7 on 2024-01-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_clients', '0010_alter_taxclient_participation_accounting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxclient',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='taxclient',
            name='delivery_building',
        ),
        migrations.RemoveField(
            model_name='taxclient',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='taxclient',
            name='delivery_prefecture',
        ),
        migrations.RemoveField(
            model_name='taxclient',
            name='delivery_same',
        ),
        migrations.RemoveField(
            model_name='taxclient',
            name='delivery_zipcode',
        ),
    ]
