# Generated by Django 4.2.7 on 2024-01-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_clients', '0012_remove_taxclient_mail_magazine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxclient',
            name='local_tax_method',
        ),
        migrations.RemoveField(
            model_name='taxclient',
            name='national_tax_method',
        ),
        migrations.RemoveField(
            model_name='taxclient',
            name='resident_tax_method',
        ),
        migrations.RemoveField(
            model_name='taxclient',
            name='withholding_method',
        ),
    ]
