# Generated by Django 4.2.7 on 2024-01-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_by',
            new_name='user',
        ),
    ]
