# Generated by Django 4.2.7 on 2024-01-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_rename_completed_todo_recurrence_todo_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('', '-----'), ('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月'), ('yearly', '毎年')], default='', max_length=10),
        ),
    ]
