# Generated by Django 4.2.7 on 2024-01-16 22:06

from django.db import migrations, models
import offices.models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_alter_customuser_office_alter_office_office_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_id',
            field=models.CharField(default=offices.models.generate_office_id, max_length=12, unique=True),
        ),
    ]
